# AI Coding Agent Workflow
# Copy this file to your repo: .github/workflows/ai-agent.yml
#
# Required Secrets:
#   - ANTHROPIC_API_KEY (for Claude models)
#   - OPENAI_API_KEY (for GPT-4/Codex)
#   - GOOGLE_API_KEY (for Gemini models)
#   - DEEPSEEK_API_KEY (for DeepSeek models)
#   - MISTRAL_API_KEY (for Mistral models)
#
# You only need to set the keys for the models you plan to use.

name: AI Coding Agent

on:
  issues:
    types: [labeled]

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: number
      model:
        description: 'Model override (optional)'
        required: false
        type: choice
        options:
          - ''
          - 'claude-sonnet-4-20250514'
          - 'claude-opus-4-20250514'
          - 'gpt-4o'
          - 'gpt-4-turbo'
          - 'gemini/gemini-1.5-pro'
          - 'gemini/gemini-1.5-flash'

jobs:
  ai-agent:
    # Only run when 'ai-task' label is added
    if: |
      (github.event_name == 'issues' && github.event.label.name == 'ai-task') ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout AI Pipeline agent
        uses: actions/checkout@v4
        with:
          repository: reachkrishnaraj/ai-coding-agent-pipeline
          path: agent

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r agent/agent-runner/requirements.txt

      - name: Determine issue number
        id: issue
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "number=${{ inputs.issue_number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Run AI Agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          MODEL_ARG=""
          if [ -n "${{ inputs.model }}" ]; then
            MODEL_ARG="--model ${{ inputs.model }}"
          fi

          python agent/agent-runner/agent.py \
            --repo ${{ github.repository }} \
            --issue ${{ steps.issue.outputs.number }} \
            $MODEL_ARG

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.issue.outputs.number }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: '❌ AI Agent failed to process this task. Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            });
